# Generated by Django 5.0 on 2023-12-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=200)),
                ('ext', models.CharField(max_length=3)),
                ('development', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('eststore', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
