# Generated by Django 5.0 on 2024-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_ext_alter_store_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='ext',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
