# Generated by Django 5.0 on 2024-01-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseconcept',
            name='description',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
