# Generated by Django 5.0 on 2024-01-08 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0002_alter_warehouseconcept_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WereHouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.products')),
                ('werehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouses.warehouses')),
            ],
        ),
    ]
