# Generated by Django 5.0 on 2024-01-17 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productlistdetails_predlp'),
        ('warehouses', '0003_werehousestock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WereHouseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('typemovement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouses.typemovement')),
                ('usercreated', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('werehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouses.warehouses')),
                ('werehouseconcept', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouses.warehouseconcept')),
            ],
        ),
        migrations.CreateModel(
            name='WereHouseMovementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canmov', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.products')),
                ('usercreated', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('werehousemovement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouses.werehousemovement')),
            ],
        ),
    ]
