# Generated by Django 5.0 on 2024-01-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_werehousemovement_werehousemovementdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemovement',
            name='addition',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
