# Generated by Django 5.0 on 2024-01-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_typemovement_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='werehousemovement',
            name='observations',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
