# Generated by Django 5.0 on 2024-01-22 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productlistdetails_predlp'),
        ('warehouses', '0006_werehousemovement_observations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WereHousePurchasing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecrem', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('totcom', models.FloatField()),
                ('observations', models.TextField(blank=True, max_length=150)),
                ('usercreated', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WereHousePurchasingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candco', models.BigIntegerField()),
                ('totdco', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.products')),
                ('werehousepurchasing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouses.werehousepurchasing')),
            ],
        ),
    ]
