# Generated by Django 5.0 on 2024-02-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0005_remove_profileuser_user_remove_profileuser_warehouse_and_more'),
        ('warehouses', '0008_werehousepurchasingdetails_predco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='warehouse',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='warehouses.warehouses'),
            preserve_default=False,
        ),
    ]
