# Generated by Django 5.0 on 2024-02-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0006_remove_profileuser_warehouse_profileuser_warehouse'),
        ('warehouses', '0008_werehousepurchasingdetails_predco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouses.warehouses'),
        ),
    ]
