# Generated by Django 5.0 on 2024-01-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productlist_productlistdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='name',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
