# Generated by Django 5.0 on 2024-01-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistdetails',
            name='predlp',
            field=models.FloatField(),
        ),
    ]
